ScopeLift/umbra-protocol

- app/src/components/BaseInput.vue
- app/src/components/ConnectWallet.vue
- app/src/components/InputPrivateKey.vue
- app/src/components/TheTutorial.vue
- app/src/css/app.sass
- app/src/layouts/BaseLayout.vue
- app/src/pages/Home.vue
- app/src/pages/Send.vue
- app/src/pages/Setup.vue
- app/src/pages/Withdraw.vue
- app/src/store/user/mutations.js
- app/src/store/user/state.js
Changes:
- Add interface for entering private key with placeholder explaining what will happen afterwards
- Add warning to header so users do not use accounts that hold funds on mainnet
- Add tutorial to home page explaining how to use the app
- Small change to login flow so you can navigate to pages without logging in first
- Cleanup CSS and improve mobile appearance
> More frontend updates

- contracts/.gitignore
- contracts/.openzeppelin/project.json
- contracts/.openzeppelin/ropsten.json
- contracts/networks.js
Deployment:
* [Umbra](https://ropsten.etherscan.io/address/0x264063408fD1bdC703083AE083c813240A024B7f)
* [UmbraPaymaster](https://ropsten.etherscan.io/address/0xcca839b94ba3b52b8f82485b14856602e8635eba)
> Configuration For Ropsten Deployment

- contracts/contracts/Umbra.sol
- contracts/test/sample-data.js
- contracts/test/umbra-gsn-test.js
- contracts/test/umbra-test.js
* Remove unneeded parameters from the send method signatures and
the emitted event
* Update tests to reflect the new structure
This is the contract side of #31
> Modify the contracts to support new encryption scheme

- contracts/contracts/Umbra.sol
- contracts/test/umbra-test.js
> Add toll commitment parameter to the sendETH method

- contracts/scripts/deploy.js
> Enhanced to create network-latest.json file

- contracts/contracts/Umbra.sol
- contracts/contracts/open_gsn/UmbraRelayRecipient.sol
- contracts/test/umbra-gsn-test.js
- contracts/test/umbra-test.js
- contracts/test/utils.js
- frontend/src/components/AccountReceiveTable.vue
- umbra-js/src/classes/Umbra.ts
- umbra-js/src/types.ts
- umbra-js/test/Umbra.test.ts
closes #98 
closes #74 
closes #18
> Various Contract Enhancements

- frontend/src/components/AccountReceiveTable.vue
- frontend/src/components/ConnectWallet.vue
- frontend/src/components/ConnectWalletCard.vue
- frontend/src/layouts/BaseLayout.vue
- frontend/src/pages/AccountReceive.vue
- frontend/src/pages/AccountSend.vue
- frontend/src/pages/AccountSetup.vue
- frontend/src/pages/Contact.vue
- frontend/src/pages/FAQ.vue
- frontend/src/router/index.ts
- frontend/src/router/routes.ts
- frontend/src/store/wallet.ts
- frontend/src/utils/alerts.ts
- umbra-js/src/utils/ens.ts
- umbra-js/src/utils/utils.ts
Closes #105, closes #108, closes #109
Changes:
- Fix bug on receive table to show addresses properly. Now using the same format as MetaMask, e.g. `0x1234...abcd`
- Add contact and FAQ pages. FAQ page just has a few placeholder questions with "TODO" as the answer for now
-  As part of this, we remove route guards, so you can now visit any page directly (instead of being forced to go through the home page) and will be asked to connect your wallet as needed
- Add support for all ENS domains to the Send page
- Small improvement to the user wallet info is saved to the store, which provides better UX
> Frontend improvements

- contracts/contracts/MockHook.sol
- contracts/contracts/Umbra.sol
- contracts/test/umbra-gsn-test.js
- contracts/test/umbra-test.js
Would love to understand why this doesn't seem to run on the contract directory in the commit hook? cc @wildmolasses
> Run prettier on contracts directory

- contracts/contracts/Umbra.sol
- contracts/test/umbra-gsn-test.js
- contracts/test/umbra-hook-test.js
- contracts/test/umbra-test.js
- contracts/test/utils.js
- umbra-js/src/classes/Umbra.ts
- umbra-js/test/Umbra.test.ts
- yarn.lock
> Implement Contract Audit Feedback

- frontend/src/components/AccountReceiveTable.vue
- frontend/src/pages/AccountSend.vue
- frontend/src/pages/FAQ.vue
- frontend/src/utils/ethers.ts
- umbra-js/src/classes/DomainService.ts
- umbra-js/src/classes/KeyPair.ts
- umbra-js/src/classes/RandomNumber.ts
- umbra-js/src/classes/Umbra.ts
- umbra-js/src/types.ts
- umbra-js/src/utils/utils.ts
- umbra-js/test/DomainService.test.ts
- umbra-js/test/KeyPair.test.ts
- umbra-js/test/RandomNumber.test.ts
- umbra-js/test/Umbra.test.ts
- umbra-js/test/cns.test.ts
- umbra-js/test/ens.test.ts
- umbra-js/test/utils.test.ts
- umbra-js/test/utils.ts
Fixes from Least Authority audit report:
- "Issue A: Stealth Addresses Provide Only 64-Bit of Security by Default": Fixed by 02288fabc92a2afe29600fe742da275e7ce9243c
- e3d9e08f7b761326f29b56acc40f04e81ca0b8c2 is outside the audit scope, but includes the corresponding frontend changes
- "Issue B: Group Membership of Public Keys Not Checked": Fixed by 2e03fef8cfe2b9a0e67baac37ce9138e9b83848b
- "Suggestion 1: Test Domain Updating Code": Fixed by e9bfecceb7c7ddd384997162e679e2a695669da6
- "Suggestion 3: Document Security Trade-Offs": Fixed by f82ecc55c5c2d6e4d2dca7ac706a754e718e95a7
Other fixes:
- Fix improperly named function inputs: 59eef1bb907a260fa65ca806875ee5d1cd03c6ac
> Audit fixes

- frontend/src/layouts/BaseLayout.vue
- frontend/src/pages/PrivacyPolicy.vue
- Adjust the privacy policy to clarify the IP logging situation
- Add support email to the footer
> Minor Pre-Launch Copy Tweaks

- frontend/src/layouts/BaseLayout.vue
- frontend/src/utils/alerts.ts
Handles this error:
And this style bug:
> Small frontend bugfixes

- README.md
- frontend/README.md
- frontend/package.json
- frontend/src/pages/FAQ.vue
Makes various improvements and updates to the main README and adds a simple README to the frontend subdirectory.
closes #139 
closes #204 
Creating a better diagram is pushed to #215
> Readme improvements

- frontend/src/components/AccountReceiveTable.vue
- frontend/src/components/AccountReceiveTableWithdrawConfirmation.vue
- frontend/src/components/BaseInput.vue
- frontend/src/components/WithdrawForm.vue
- frontend/src/css/app.sass
- frontend/src/layouts/AddressSettings.vue
- frontend/src/layouts/BaseLayout.vue
- frontend/src/layouts/HeaderLinks.vue
- frontend/src/pages/AccountReceive.vue
- frontend/src/pages/AccountSetup.vue
- frontend/src/pages/Home.vue
- frontend/src/pages/PrivacyPolicy.vue
- frontend/src/pages/TermsOfService.vue
https://gitcoin.co/issue/ScopeLift/umbra-protocol/218/100026261
> Improve Mobile Browser Responsiveness

- contracts/contracts/StealthKeyRegistry.sol
- contracts/hardhat.config.ts
- contracts/package.json
- contracts/test/stealth-key-registry-test.ts
- yarn.lock
Implements the contract component of #214. Includes an EIP-712 compatible meta tx enabled method for updating stealth keys.
> Implement and Test StealthKeyRegistry Contracts

- frontend/src/components/BaseSelect.vue
- frontend/src/components/models.ts
- frontend/src/layouts/AddressSettings.vue
- frontend/src/layouts/BaseLayout.vue
- frontend/src/layouts/NetworkDropdown.vue
- frontend/src/store/wallet.ts
- frontend/src/utils/ethers.ts
- frontend/src/utils/utils.ts
> Add Network Selector

- frontend/src/components/AccountReceiveTable.vue
- frontend/src/layouts/BaseLayout.vue
- frontend/src/store/wallet.ts
- frontend/src/utils/address.ts
> fix from format in card

- contracts/deploy-history/polygon-2021-10-29T18:50:56.054Z.json
- contracts/deploy-history/polygon-latest.json
- contracts/deploy-history/registry-polygon-2021-10-29T18:56:56.540Z.json
- contracts/deploy-history/registry-polygon-latest.json
- contracts/hardhat.config.ts
- contracts/package.json
- contracts/scripts/deployParams-registry.json
- contracts/scripts/deployParams.json
- yarn.lock
> Configure and deploy Umbra + Registry to Polygon

- umbra-js/src/classes/Umbra.ts
Note: Had to commit with `--no-verify` due a lint error that is not clear to me. Any ideas @mds1?
> Disable TheGraph for Rinkeby due to technical issues/outage

- frontend/src/components/Avatar.vue
closes https://github.com/ScopeLift/umbra-protocol/issues/300
> fix/style: fix build error, align avatar container

- frontend/src/layouts/BaseLayout.vue
> Support avatars on mobile

- frontend/src/store/wallet.ts
Not yet tested, needs testing before merging
> fix: clear more state when switching networks

- contracts-core/package.json
- frontend/package.json
- umbra-js/package.json
- umbra-js/test/StealthKeyRegistry.test.ts
- umbra-js/test/Umbra.test.ts
- umbra-js/test/utils.test.ts
- yarn.lock
* Upgrades yarn and node versions used during development (via volta config)
* Upgrades Ethers to the latest versions
closes #321
> Upgrade Ethers

- frontend/src/utils/address.ts
This simple solution seems to work even when the API url is wrong.
> Add try-catch block to POAP API call

- .gitmodules
- contracts-periphery/Makefile
- contracts-periphery/foundry.toml
- contracts-periphery/test/UniswapWithdrawHook.fork.1.t.sol
- contracts-periphery/test/utils/DSTestPlus.sol
Changes: 
- Use `vm.createSelectFork` cheatcode.
- Update foundry.toml
- Update dependencies including solmate
> Streamline periphery fork tests

- frontend/src/components/AccountReceiveTableWithdrawConfirmation.vue
- umbra-js/src/utils/utils.ts
Intentionally leaving as a draft until the Nitro upgrade is complete. This should not be merged until then, which is in ~2 hours
> fix: arbitrum now has same gas prices as L1

- umbra-js/src/ethers.ts
- umbra-js/src/utils/utils.ts
Fixes https://github.com/ScopeLift/umbra-protocol/issues/391
> fix: properly detect signed txs on arbitrum

- contracts-core/deploy-history/goerli-2022-10-05T22:15:08.170Z.json
- contracts-core/deploy-history/goerli-latest.json
- contracts-core/scripts/deployParams.json
> Deploy Umbra to Goerli testnet

- frontend/package.json
- frontend/src/components/AccountReceiveTable.vue
- frontend/src/store/wallet.ts
- frontend/src/utils/address.ts
- umbra-js/package.json
- umbra-js/src/utils/cns.ts
- umbra-js/src/utils/utils.ts
- umbra-js/test/cns.test.ts
- yarn.lock
Upgraded unstoppable domain package and added reverse resolution 
--- 
[umbra integration .webm](https://user-images.githubusercontent.com/72156537/184285064-7d1b3f4e-2c9f-4c50-af9d-1fcd55b42e4b.webm)
Reverse Resolution : 
--- 
You can also use our Unstoppable Domains to check lookup Functionality : blockdudes.blockchain resolved to 0x89f9798a8d8bac15a47031779cc6aa08d8059c52
> feat: unstoppable domains upgrade + reverse resolution

- frontend/src/i18n/locales/en-us.json
- frontend/src/i18n/locales/zh-cn.json
- frontend/src/pages/AccountSend.vue
Closes #362 
Description:
I added two modals one for when "send using recipient's public key is selected" and another on when the send is clicked. I based the copy on the issue and open to improving it.
[Screencast from 10-11-2022 07:59:35 PM.webm](https://user-images.githubusercontent.com/12705146/195219578-a6d1ad3c-3052-4d51-8830-851525f61875.webm)
> Add modals for advanced mode

- frontend/src/global.d.ts
- frontend/src/store/wallet.ts
We do not prompt metamask if it is locked.
[Screencast from 10-26-2022 09:41:27 PM.webm](https://user-images.githubusercontent.com/12705146/198171249-f5363d56-2aff-4ebb-b120-d69acb134f86.webm)
> Do not prompt locked metamask

- .github/workflows/ci.yaml
- contracts-periphery/foundry.toml
- contracts-periphery/script/Deploy.s.sol
- contracts-periphery/src/UmbraBatchSend.sol
- contracts-periphery/src/UniswapWithdrawHook.sol
- contracts-periphery/src/interface/IUmbra.sol
- contracts-periphery/src/interface/IUniswapV3SwapCallback.sol
- contracts-periphery/test/UmbraBatchSend.t.sol
- contracts-periphery/test/UniswapWithdrawHook.fork.1.t.sol
- contracts-periphery/test/gas/UmbraBatchSend.gas.t.sol
- contracts-periphery/test/utils/DeployUmbraTest.sol
Ref https://book.getfoundry.sh/tutorials/best-practices and https://github.com/ScopeLift/foundry-template/
See commit messages for more info on some of the changes
> best practices + style guide updates

- .github/workflows/ci.yaml
- .gitignore
- contracts-core/package.json
- contracts-periphery/Makefile
- contracts-periphery/package.json
- package.json
- umbra-js/.nycrc
- umbra-js/package.json
- I fixed the existing coverage commands and added a monorepo command. I also added coverage to the github workflow
Closes #323
> Fix coverage and add to build

- .github/workflows/ci.yaml
- contracts-periphery/script/Deploy.s.sol
To test, run: 
1. `anvil --fork-url <ETH-RPC-URL> --fork-block-number 15971478`
2. `forge script script/Deploy.s.sol --private-key 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80 --broadcast --slow --fork-url http://127.0.0.1:8545`
Goerli deployed contract address `0xDf4B5B2C08A77078c05176D8dFAb6274D54215e9`
> Add batchSend deploy script

- frontend/src/boot/i18n.ts
- frontend/src/store/settings.ts
https://user-images.githubusercontent.com/61768337/208541950-f0605322-8825-40d6-ac02-c1b7eba2aa88.mov
> i18n param query fix

- frontend/src/pages/AccountReceive.vue
- frontend/src/store/settings.ts
https://user-images.githubusercontent.com/61768337/208781387-0895ae5d-2555-4612-9d0f-ed387e355163.mov
> Fix scanning with private key issue

- frontend/src/store/wallet.ts
Note: I think there's one more place we need makeRaw -- namely [here](https://github.com/ScopeLift/umbra-protocol/blob/1fe4ef016b687d6b6c45e7487e41abca105c5e59/frontend/src/store/wallet.ts#L344-L345) -- but I haven't been able to verify yet
> Quasar v2 Fix Sends and Setup

- frontend/src/css/app.sass
- frontend/src/layouts/BaseLayout.vue
Recommend turning off whitespace for a cleaner diff, since everything was indented by being wrapped in a new div.
For now turning off this banner needs a new deploy, since we have auto deploys on merge to master setup this seems fine for now and we can improve it later if we need
> feat: add hardcoded donation banner

- frontend/src/i18n/locales/en-us.json
- frontend/src/i18n/locales/zh-cn.json
- frontend/src/layouts/BaseLayout.vue
https://user-images.githubusercontent.com/61768337/213568025-931c4fff-9491-42b5-9483-aa80b23324c8.mov
> Localize alert banner

- frontend/src/i18n/locales/en-US.json
- frontend/src/i18n/locales/zh-CN.json
- frontend/src/layouts/BaseLayout.vue
> fix: add missing connect wallet translation

- frontend/src/components/BaseInput.vue
> fix: input field button is always inside input field

- frontend/src/i18n/locales/zh-CN.json
> Fix i18n key mismatch in FAQ page

- frontend/.eslintrc.js
- frontend/package.json
- frontend/src/components/AccountReceiveTable.vue
- frontend/src/components/AccountReceiveTableWithdrawConfirmation.vue
- frontend/src/pages/AccountReceive.vue
- frontend/src/pages/AccountSend.vue
- frontend/src/store/wallet.ts
- frontend/src/utils/address.ts
- frontend/src/utils/payment-links.ts
- frontend/src/worker/filter.worker.ts
- frontend/src/worker/worker.ts
- umbra-js/package.json
- umbra-js/tsconfig.json
> changes to publish umbra-js

- frontend/src/components/models.ts
- frontend/src/layouts/BaseLayout.vue
- frontend/src/store/settings.ts
- frontend/src/store/wallet.ts
* We need to manually setLocale in the wallet when we want to change the translations.
Closes #449
> Fix web3 onboard translation

- frontend/src/store/wallet.ts
> fix: markRaw on rawProvider to ensure `this` is properly bound

- .github/workflows/ci.yaml
- frontend/src/i18n/locales/en-US.json
- frontend/src/i18n/locales/zh-CN.json
- frontend/src/pages/AccountSend.vue
- umbra-js/src/utils/utils.ts
> Send native token max without dust

- frontend/src/pages/AccountSend.vue
- Send history link should not be showing
> Hide send history link

- .github/workflows/ci.yaml
- umbra-js/src/utils/utils.ts
Closes https://github.com/ScopeLift/umbra-protocol/issues/479
> fix: handle tx type 120 on arbitrum (pre nitro tx)

- frontend/src/components/AccountReceiveTable.vue
Closes https://github.com/ScopeLift/umbra-protocol/issues/497
> perf: use multicall to lookup stealth balances

- frontend/src/i18n/locales/en-US.json
- frontend/src/i18n/locales/zh-CN.json
- frontend/src/layouts/BaseLayout.vue
> Add back gitcoin banner

- frontend/src/i18n/locales/en-US.json
- frontend/src/i18n/locales/zh-CN.json
- frontend/src/utils/address.ts
- frontend/src/utils/umbra-api.ts
- umbra-js/src/utils/utils.ts
- Add gitcoin contributor warning
[Screencast from 2023-04-25 08-41-26.webm](https://user-images.githubusercontent.com/12705146/234279909-dde6b3b1-1180-49c2-8d07-5e89e323b96c.webm)
Closes #469
> Warn withdrawl to gitcoin contributor address

- umbra-js/src/classes/Umbra.ts
- umbra-js/test/Umbra.test.ts
> feat: goldsky subgraph testing

- contracts-core/deploy-history/sepolia-2023-05-22T21:10:43.386Z.json
- contracts-core/deploy-history/sepolia-latest.json
- contracts-core/hardhat.config.ts
- contracts-core/package.json
- contracts-core/scripts/deploy.js
- contracts-core/scripts/deployParams.json
- yarn.lock
> Deploy Umbra core contracts to Sepolia Testnet

- frontend/src/utils/address.ts
Resolves https://github.com/ScopeLift/umbra-protocol/issues/512
> fix: handle ENS names with invalid characters

- frontend/src/pages/AccountReceive.vue
- frontend/src/store/settings.ts
- frontend/src/store/wallet.ts
- umbra-js/src/classes/Umbra.ts
- umbra-js/src/types.ts
- A user can now specify the start and end block in umbra and see the results for only those blocks
Closes #513
> Hook up advanced block filtering to the graph subgraph

- contracts-core/deploy-history/gnosis_chain-2023-06-01T16:05:15.723Z.json
- contracts-core/deploy-history/gnosis_chain-latest.json
- contracts-core/hardhat.config.ts
- contracts-core/scripts/deployParams.json
> Deploy core contracts to Gnosis Chain

- umbra-js/package.json
> Bump umbra-js package version

- frontend/src/pages/AccountSend.vue
Tokens won't be supported until https://github.com/ScopeLift/umbra-api/pull/115 is merged.
> Add Sepolia to batchSend supported chains

- frontend/src/pages/AccountSend.vue
- frontend/src/store/wallet.ts
Fixes Umbra fee not being adding to summary total amount
Before:
After:
> Fix batchSend summary

- frontend/src/pages/AccountSend.vue
- frontend/src/utils/account-send.ts
- frontend/test/account-send.test.ts
- Add history button to send page
- Store send in account send history
>  Add account encryption to batch send

- frontend/src/pages/AccountSend.vue
> Fix batchSend form validation on change Closes #531

- frontend/package.json
- umbra-js/package.json
- yarn.lock
- Bump @unstoppabledomains/resolution to 8.5.0
Closes #561
> Fix failing CNS test

- frontend/src/i18n/locales/en-US.json
- frontend/src/i18n/locales/zh-CN.json
- frontend/src/layouts/BaseLayout.vue
- frontend/src/pages/AccountSend.vue
- frontend/src/store/settings.ts
- Add toggle in settings for send history, default to true
Closes #545
> Add toggle to turn off send history

- frontend/src/css/app.sass
- frontend/src/pages/AccountReceive.vue
Closes #569 
Before:
https://github.com/ScopeLift/umbra-protocol/assets/61768337/81ead8bf-39c3-490c-94ab-2fde789a0bc8
After: 
https://github.com/ScopeLift/umbra-protocol/assets/61768337/38d2f130-528b-45ab-bb42-39ddfeb6dea8
> On receive page, ask user to setup account if unregistered

- frontend/src/components/AccountReceiveTable.vue
- frontend/src/i18n/locales/en-US.json
- frontend/src/i18n/locales/zh-CN.json
- frontend/src/utils/address.ts
> Add heuristics for same sender and registered address

- frontend/src/components/AccountReceiveTable.vue
- frontend/src/components/LoadingSpinner.vue
> Use em instead of rem for icon size

- umbra-js/src/classes/Umbra.ts
- umbra-js/test/Umbra.test.ts
> Remove check for window in Umbra-js

- frontend/src/pages/AccountSend.vue
When submitting in advanced mode with use public key checked the final confirmation modal does not close. Now, it should close.
Closes #511
> Close modal when submit is clicked

- frontend/src/components/BaseTooltip.vue
- Tooltip should now be visible in dark mode
Closes #599
> Add dark-toggle to tooltip

- frontend/src/i18n/locales/en-US.json
- frontend/src/i18n/locales/zh-CN.json
- frontend/src/pages/AccountSend.vue
`isValidBatchSendAmount` function closes #601 
https://github.com/ScopeLift/umbra-protocol/assets/61768337/3f7c694f-ea65-4319-b506-294d6876e0ec
> Enable BatchSend on Arbitrum and add `isValidBatchSendAmount`

- frontend/src/pages/AccountReceive.vue
- Check for advanced mode on mount
Closes #522
> Don't automatically scan for advancedMode

- umbra-js/src/classes/Umbra.ts
> Change query to use id instead of timestamp

- frontend/src/pages/AccountSend.vue
> Use BigNumber for `summaryAmount` and use `humanizeTokenAmount`

- frontend/src/pages/AccountSent.vue
> Add debug logs on sent

- umbra-js/src/classes/Umbra.ts
- umbra-js/test/Umbra.test.ts
closes. #612 
Merge this after https://github.com/ScopeLift/umbra-subgraph/pull/5
> Sort announcements by id

- frontend/src/pages/AccountSend.vue
> Enable batchSend on all networks

- .github/workflows/ci.yaml
- Trigger builds on pushed to master
> Allow builds on master

- frontend/src/store/wallet.ts
> Added a retry mechanism to getRegisteredStealthKeys

- contracts-core/hardhat.config.ts
This seems to fix some of the dependabot PR CI errors.
> Remove Infura dependence in `contracts-core`

- frontend/src/layouts/BaseLayout.vue
> Enable Gitcoin round 20 banner

- frontend/src/components/AccountReceiveTable.vue
- frontend/src/i18n/locales/en-US.json
- frontend/src/pages/AccountReceive.vue
> Display most recent Umbra announcement time/block on receive page
