umbra-js/README.md
umbra-js/classes/KeyPair.js
umbra-js/test/KeyPair.test.js

Add support for specifying recipient / generating `KeyPair` instance by providing a transaction hash. The public key of the sender of the specified transaction is recovered and used to instantiate the `KeyPair` instance.

Can now specify recipient by tx hash and recover public key

---

umbra-js/classes/KeyPair.js
umbra-js/classes/RandomNumber.js
umbra-js/index.js
umbra-js/package-lock.json
umbra-js/package.json
umbra-js/test/KeyPair.test.js
umbra-js/test/RandomNumber.test.js
umbra-js/utils/utils.js

- Adds ECIES encryption to KeyPair class, implemented with [`eccrypto`](https://github.com/bitchan/eccrypto/)
- Rename package from `umbra-protocol` to `umbra-js`
- Fix bug in random number class where returned hex strings would have leading zeros truncated.
Encryption/decryption requires the `Buffer` class which works in node, but does not exist natively in the browser. Will add support for that in a separate PR.

Add encryption to umbra-js

---

app/package-lock.json
app/package.json
app/src/components/AccountSetupChoosePassword.vue
app/src/components/AccountSetupEnsCheck.vue
app/src/components/AccountSetupEnsConfig.vue
app/src/components/AccountSetupPrivateKey.vue
app/src/components/BaseButton.vue
app/src/components/BaseInput.vue
app/src/components/InputPrivateKey.vue
app/src/components/TheTutorial.vue
app/src/components/UnlockAccount.vue
app/src/mixins/cryptography.js
app/src/pages/Home.vue
app/src/pages/Setup.vue
app/src/pages/Withdraw.vue
app/src/store/user/mutations.js
app/src/store/user/state.js

Closes #15
Updated the account setup process to walk through the steps outlined in #15. The withdraw process is also implemented, but without steps 10–16 where we scan the blockchain for announcements.
Before testing, you'll need to remove the `vnd.umbra-v0-signature` record from your Ropsten ENS account. You can do this at https://app.ens.domains/name/yourDomain.eth
Note that this PR only covers the initial implementation, and I want to take another pass at the code for security reasons (e.g. minimizing the time unencrypted data is stored in state)

Implement pbkdf

---

contracts/contracts/Umbra.sol
contracts/test/umbra-test.js

The primary goal of this change is to prevent the need for an
extra flag, written to storage during Umbra sends, formerly used to
prevent stealth address re-use.
In normal usage of the protocol, addresses would not be re-used, but
someone could call the contract methods with an address that had already
received funds. There is no downside to this, except in the case of token
payments, where the funds are held in the contract until withdrawn, and
the balance of each stealth address is held in the contract. In such a
case, re-using the address would cause the prior balance data to be
overwritten, effectively locking the funds.
The motivation for this change is to save gas. We want to avoid the extra
storage write without the risk of locked funds. To do this, we:
1. Allow re-use of addresses …

Save Gas By Removing Unnecessary Stealth Address Re-use Flag

---

umbra-js/src/classes/Umbra.ts
umbra-js/src/types.ts
umbra-js/test/Umbra.test.ts

Closes #80
Defines new type `ChainConfig` that can be provided when creating an instance of the Umbra class. This defines the Umbra contract address and default block to start scanning from. Umbra instances can now be created with the following options:
- Instantiation: (1) `Umbra.create` with a signer to allow calling methods, or (2) `Umbra.createReadonly` with an node URL to only allow reads
- Chain config: (1)  Don't provide a `chainConfig` to infer it from the signer/provider, or (2) provide a chain ID to use the hardcoded info, or (3) enable it to be fully custom
This results in 3 * 2 = 6 possible ways to create an Umbra class
Other notes:
- The Umbra tests now fetch the latest Ropsten block number and always start scanning from there, so you no longer need to manually update that …

Add ability to customize chainConfig

---

umbra-js/package.json
yarn.lock

Closes #78
Breaking changes were introduced after this in v1.10.1, so we pin the version to ensure a compatible version is always installed. See the links below for more information:
- https://github.com/unstoppabledomains/resolution/issues/112
- https://github.com/unstoppabledomains/resolution/blob/master/CHANGELOG.md
To test:
1. Update the `startBlock` values in `Umbra.ts` with the latest Ropsten block number
2. Install packages at the root with `yarn`,
3. Run `cd umbra-js` and `yarn test`. All tests should pass with 2 that have always been skipped.

Pin @unstoppabledomains/resolution to v1.9.0

---

umbra-js/src/classes/Umbra.ts
umbra-js/src/types.ts
umbra-js/test/Umbra.test.ts

Closes #79 
Also refactors methods to take in exactly what is needed. So we no longer associate keys or a signer with the Umbra class—just a provider—and methods take keys or singers as inputs when needed

Add umbrajs withdraw methods

---

contracts/.eslintrc.js
contracts/contracts/open_gsn/UmbraForwarder.sol
contracts/contracts/open_gsn/UmbraPaymaster.sol
contracts/package.json
contracts/tasks/clean.ts
contracts/test/umbra-gsn-test.js
contracts/test/umbra-test.js
yarn.lock

This PR upgrades OpenGSN to the latest mainnet version, along with the tests for OpenGSN support. It also cleans up the `UmbraForwarder` stub to include the absolute minimum set of functionality needed to comply with the GSN architecture without actually doing the validation inside the forwarder contract.
closes #86 
closes #81

Upgrade to OpenGSN v2.1

---

contracts/hardhat.config.ts
contracts/package.json
frontend/package.json
frontend/src/components/models.ts
notes.md
package.json
umbra-js/package.json
umbra-js/test/DomainService.test.ts
umbra-js/test/cns.test.ts
umbra-js/test/utils.test.ts

This small set of changes enables us to install the monorepo as a dependency of another repo using a git url
other repos can install @umbra as a dependency using a github url. over the course of working on this i explored publishing and packing concepts and can definitely help when it comes time to publish to npm. once our packages are on npm then we could require them as packed versions instead of the entire monorepo. but for now, using the whole monorepo as a dependency doesn't feel terrible and gives us a few things:
- other repos can use types defined in @umbra. for example, we can define what a request body looks like in @umbra/frontend and then require that type in an umbra-api route.
- other repos can use contracts (useful if we want to run tests against a local hardhat deploy) and …

Enable monorepo to be required as dependency

---

contracts/contracts/IUmbraHookReceiver.sol
contracts/contracts/MockHook.sol
contracts/contracts/Umbra.sol
contracts/contracts/UmbraHookable.sol
contracts/test/umbra-hook-test.js
contracts/test/umbra-test.js
contracts/test/utils.js
umbra-js/src/classes/Umbra.ts

* Extracts common withdrawal functionality into shared internal methods
* Defines an interface for Umbra post withdraw hooks
* Implements withdraw methods that call this hook after the token withdrawal completes
* Adds tests exercising post withdraw hook usage
TODO:
closes #37

Implement And Test Post Withdraw Hooks

---

frontend/src/components/AccountReceiveTable.vue
frontend/src/components/AccountReceiveTableWarning.vue
frontend/src/components/BaseButton.vue
frontend/src/css/app.sass
frontend/src/utils/address.ts

Closes #107
For now, we show a modal that gives two options: Learn More, or Acknowledge the Risks. The latter continues with withdrawal, and the former links to the FAQ page. Once we update the FAQ / write more docs, we can change where that links to if we want

Warn about bad privacy

---

frontend/src/components/AccountReceiveTable.vue
frontend/src/components/BaseInput.vue
frontend/src/css/app.sass
frontend/src/layouts/BaseLayout.vue
frontend/src/pages/AccountReceive.vue
frontend/src/pages/AccountSend.vue
frontend/src/store/settings.ts
frontend/src/utils/address.ts
umbra-js/src/classes/Umbra.ts
umbra-js/src/utils/utils.ts

Closes #124, closes #106 (moves one task from #106 into #135 since I want to think of the cleanest way to do that and there's more pressing functionality first). Changes:
1. Export Private Key Of Receiving Stealth Address
2. Define start and end blocks for receive Announcement scanning
3. Send to a general ETH address using recovered TX pub key, transaction hash, or specific Public Key
4. Include a Payload Extension when sending
5. Display Payload Extension on receives (should this be there even in non-advanced mode?)
Notes: 
- The advanced toggle is in the footer
- Items 1, 2, and 3 are advanced-mode only feature. Items 4 and 5 are always present
- When advanced mode is on, the 🧙 emoji is shown in the top right with tooltip on hover. 
- Settings such as dark mode, start and end blocks, …

Advanced UI features

---

umbra-js/package.json
umbra-js/src/classes/KeyPair.ts
umbra-js/src/utils/cns.ts
umbra-js/src/utils/utils.ts
umbra-js/test/KeyPair.test.ts
umbra-js/test/RandomNumber.test.ts
umbra-js/test/utils.test.ts
yarn.lock

(Built off the branch in #133, so that needs to be merged first, then we'll rebase this against the master)
- Implements noble-secp256k1 for all ECC operations
- A bit of cleanup (remove unneeded padHex method)
- Need to double check that we're not using elliptic behind the scenes from an ethers method
- We also change the shared secret computation, such that the shared secret is now the hash of the resulting point, instead of the point itself. This is preferred as in theory it should make the output symmetric keys more uniformly distributed. Consequently, **this PR is a breaking change** and once merged, past sends will no longer display in the UI when building locally

Switch to noble-secp256k1

---

umbra-js/package.json
umbra-js/src/classes/KeyPair.ts
umbra-js/src/classes/RandomNumber.ts
umbra-js/src/types.ts
umbra-js/src/utils/ens.ts

- Replaces `ethers.wallet.createRandom()` with noble-secp256k1's `randomPrivateKey()`, since `createRandom()` ultimately passes through elliptic at one point
- Removes the `eth-ens-namehash` package for getting the namehash of ENS names and we now use the ethers.js method instead

Remove elliptic

---

umbra-js/package.json
umbra-js/src/utils/utils.ts
yarn.lock

Closes #152 
(branched off #151, so figured we can just merge this into 151's branch first since this will be a much quicker PR to review/merge)

Remove unused dependencies and methods

---

frontend/tsconfig.json
umbra-js/.nycrc
umbra-js/package.json
umbra-js/src/classes/DomainService.ts
umbra-js/src/classes/KeyPair.ts
umbra-js/src/classes/Umbra.ts
umbra-js/src/utils/cns.ts
umbra-js/src/utils/ens.ts
umbra-js/src/utils/utils.ts
umbra-js/test/KeyPair.test.ts
umbra-js/test/Umbra.test.ts
umbra-js/test/cns.test.ts
umbra-js/test/ens.test.ts
umbra-js/test/utils.test.ts
umbra-js/test/utils.ts
umbra-js/tsconfig.json
yarn.lock

- Improves coverage of umbra-js files. Most code not covered by testing is either (1) setting public keys, or (2) `throw` statements from error conditions that are tricky / not clear how to get into 
- To help prevent stuck funds:
- Adds list of addresses that the Umbra class `send` method will not send to
- Adds list of keys that the KeyPair class will not initialize with
- Updates umbra-js dependencies to latest version
- Coverage script now removes builds folder before running
@wildmolasses You'll notice I also added `"skipLibCheck": true,` to the `frontend` and `umbra-js` tsconfig files to handle complaints that TS threw after upgrading dependencies. Let me know if you prefer a different way of handling this

umbra-js coverage and enhancements

---

contracts/contracts/Umbra.sol
umbra-js/.eslintignore
umbra-js/.prettierignore
umbra-js/README.md
umbra-js/package.json
umbra-js/src/classes/Umbra.ts
umbra-js/src/utils/utils.ts

- Adds a few `getAddress` checks to validate addresses + ensure we always use checksum addresses
- Add script to `package.json` to simplify umbra-js doc generation
- Add files/folders to eslintignore—the umbra-js `yarn lint` was failing and this fixes that
- In `Umbra.sol`, `ETH_TOKEN_PLACHOLDER` did not have it's visibility specified, so made it public
- Ran Prettier which formatted the README

Umbrajs input validation + other cleanup

---

frontend/src/components/AccountReceiveTable.vue
frontend/src/components/AccountReceiveTableWithdrawConfirmation.vue
frontend/src/components/BaseInput.vue

Adds the following functionality:
Tests were all manual.
Apart from the tests seen in the screenshot, I manually verified the following:
* token withdrawals still work ([tested DAI](https://rinkeby.etherscan.io/token/0x2e055eee18284513b993db7568a592679ab13188?a=0xde2087e6cd519a2fb7cf9e252b07cccb18a1f781))
* ETH withdrawals with default gas fees [still work](https://rinkeby.etherscan.io/tx/0x7eb347ce0f3bf5e18993fc92a5282f3b873fe714c806b4c78753a50f3cca4c21)
r? @mds1

Choose gas price on ETH withdrawals

---

frontend/src/components/AccountReceiveTableWithdrawConfirmation.vue

Adds the following functionality:
Tests were all manual.
I manually verified that [DAI](https://rinkeby.etherscan.io/tx/0xec206e938e9c40808d5ed9088d67eb5ca4518b7c158900f2af41dac49716a02d) and [ETH withdrawals](https://rinkeby.etherscan.io/tx/0x9194981a1393fe2a41511a1332656de5f0bad12f362605996f6b4b0c41e73a50) still work

Disable withdrawal button if fee is zero/missing

---

frontend/src/components/AccountReceiveTable.vue
frontend/src/components/AccountReceiveTableWithdrawConfirmation.vue
frontend/src/components/BaseButton.vue
frontend/src/components/BaseInput.vue
frontend/src/layouts/BaseLayout.vue
frontend/src/pages/AccountSend.vue
frontend/src/pages/FAQ.vue
frontend/src/utils/alerts.ts
frontend/src/utils/ethers.ts
frontend/src/utils/payment-links.ts
frontend/src/utils/relayer.ts
frontend/src/utils/utils.ts

Changes in this PR:
1. Lets user choose gas price when withdrawing ETH: The default gas price to use is queried from the node, and if the user wants to change it, they can. See #202 and #203 for more info / video demos
2. Adds payment links: On the send form, fill in any combination of fields and click the new "Generate Payment Link" button. This puts a URL on the clipboard that, when visited, pre-populates the form with the info in the link. It should work even if you visit the send page without a wallet connected
3. Prevents the "Unknown account #0" error when user rejects wallet connect prompt (resolves #192). More info in #205 
4. Fixes small UI error where modal is not on top of the page. More info in #205 
Thanks to @davidlaprade for helping with most of these!

Fronted features and fixes

---

frontend/src/components/AccountReceiveTable.vue
frontend/src/pages/AccountSend.vue
frontend/src/pages/AccountSetup.vue
frontend/src/pages/FAQ.vue
frontend/src/utils/alerts.ts
frontend/src/utils/ens.ts
frontend/src/utils/payment-links.ts
frontend/src/utils/utils.ts

Closes #213
I ended up sticking with Blocknative's notify.js because they have have a "UI Only" mode where you can control it manually like a generic notification library. I think their toasts look nice, they're likely familiar to many users, and it's a lot less work than building our own notification system, so using this seems like a great option.
As a result, there's two changes to this PR:
1. Transaction notifications: These use the same Blocknative notify.js library but now in "UI Only" mode. This looks and feels identical to users, and we handle the notification status manually based on the connected provider within the `txNotify` method. You can also click a notification and it will open the Etherscan link
2. Other notifications: All other notifications now use the same notify.js …

Improve notifications

---

frontend/src/components/BaseButton.vue
frontend/src/components/ConnectWallet.vue
frontend/src/layouts/BaseLayout.vue
frontend/src/store/settings.ts
frontend/src/store/wallet.ts

I fixed wallet loading and added the "Connect a wallet" button along with some refactoring.

Add connect wallet button

---

frontend/src/pages/FAQ.vue

Updates FAQ grammar. 
Most users will use the Umbra stealth key registry to send funds, so the recipient most likely keys 
**IS UPDATED TO** 
Most users will use the Umbra stealth key registry to send funds, so the recipient most likely has keys

doc: updates FAQ grammar

---

frontend/src/pages/AccountSend.vue

Updates condition when form validation happens to ensure validation run if both token value and amount are present/updated.
The issue here was the `isValidTokenAmount` is mapped to the token amount field and the error message wasn't getting triggered when the token name was being updated 
fixes https://github.com/ScopeLift/umbra-protocol/issues/265

bug: ensure form validation happens when values are present

---

frontend/src/boot/components.ts
frontend/src/components/AccountReceiveTable.vue
frontend/src/components/ProgressIndicator.vue
frontend/src/pages/AccountReceive.vue
frontend/src/worker/worker.ts
umbra-js/src/classes/Umbra.ts
umbra-js/src/index.ts
umbra-js/src/types.ts
umbra-js/test/Umbra.test.ts

* Refactor umbra-js to separate fetching from scanning announcements
* Chunk the scanning work in the frontend to prevent the UI from locking
* Show a progress bar while scanning for better UX
One weird issue: the UI flashes back to showing the loading indicator briefly after scanning is completed, but it's not clear to me why that is.

Prevent UI Blocking During Scanning and Show Progress Bar

---

frontend/src/components/AccountReceiveTableWithdrawConfirmation.vue
frontend/src/components/WithdrawForm.vue
frontend/src/pages/AccountSend.vue
frontend/src/utils/utils.ts

Makes updates to the frontend in preparation for supporting non-stablecoin
tokens on Polygon, notably WETH.
* Defines minimum amount for Polygon WETH as 0.001 on the send page
* Rounds WETH amounts, which can be well less than 0 on Polygon, to
display 6 decimals when showing fees and received amounts
Note: before the backend update for WETH support is deployed, there should be no noticeable changes in the UI from this PR. This PR can and should be reviewed, merged, and deployed ahead of the rollout of WETH support on the backend to ensure it works seamlessly on the frontend immediately.

Frontend tweaks to support WETH on Polygon

---

frontend/src/components/AccountReceiveTableWithdrawConfirmation.vue

Current behavior: If https://api.txprice.com/ is down (like it is right now), mainnet ETH withdrawals are blocked because the call to their API fails and we do not handle that error
New behavior: Catch the error and fallback to using a gas price provided by the node. @apbendi feel free to rename `tryGetGasPrice` to `safeGetGasPrice` or any other method name you prefer
If https://api.txprice.com/ is no longer down at the time of testing, you may need to manually force `getGasPrice()` to throw to confirm the behavior works as expected

fix: fallback to node's gas price if API is down

---

frontend/src/components/AccountReceiveTableWithdrawConfirmation.vue
umbra-js/src/classes/Umbra.ts

`withdrawal` function has been updated and when invoked
-  if `overrides.gasLimit` is passed ->  that value is used
-  else it will try to fetch the gasLimit via `estimateGas`
- and if any error occurs -> will default to `2100` 
fixes : https://github.com/ScopeLift/umbra-protocol/issues/262
- locally tested with debugger statements
- Additonally set the default gasLimit to 2500 and executed the withdraw -> and the gas limit was set to 21000 (by the estimateGas` function
https://polygonscan.com/tx/0x2c64a01853ad85e4e5df74d2a03bdbf8ffb269100c6cd5a05a8c46e873dac4db

fix: auto detect gaslimit on withdraw

---

frontend/package.json
frontend/src/components/Avatar.vue
frontend/src/components/Jazzicon.vue
frontend/src/layouts/AddressSettings.vue
frontend/src/layouts/BaseLayout.vue
frontend/src/store/wallet.ts
yarn.lock

Fixes #248 
When there is an [ENS avatar](https://app.ens.domains/name/nick.eth/details) associated with the wallet:
When there isn't an ENS avatar, we fall back to the jazzicon:
When we're on a chain that ENS isn't on, e.g. Polygon, we fallback to whatever avatar is on mainnet (if any):

Render ENS Avatars

---

frontend/src/components/AccountReceiveTable.vue
frontend/src/components/models.ts
frontend/src/i18n/locales/en-us.json
frontend/src/utils/umbra-api.ts

Removes special case handling of relayer response and assumes response is always a regular transaction hash.
**Must be merged and deployed at the same time as** https://github.com/ScopeLift/umbra-api/pull/54

Properly handle response from OZ relayer for all networks

---

frontend/src/i18n/locales/en-us.json
frontend/src/i18n/locales/zh-cn.json

When users who use the Chinese version of the site ask for help in the #help channel, there's an additional burden on the customer support team to ask for English translations of certain error and notification messages. Therefore, I've added English translations to some of the Chinese locale messages as shown below:

Add English to certain Chinese error messages and alerts

---

umbra-js/test/utils.test.ts

Switch to static provider with our infura id env var injected to avoid rate limiting associated with the default provider.

Stop using ethers default api keys

---

frontend/src/store/wallet.ts

Sometimes refreshing during a scan was slow (guess it needs to wait for the event loop to free up to refresh? not certain), but otherwise this seems to work as you'd expect by refreshing when you change address or network. Network changes from the app or from the wallet should both work

fix: clear all state on network/address change by refreshing

---

umbra-js/src/utils/utils.ts

Pretty much undoes https://github.com/ScopeLift/umbra-protocol/pull/388
The Nitro upgrade gave arbitrum the same gas metering as the EVM. However, there is still an L1 gas cost. This aspect of pricing is baked into the gas limit returned from eth_estimateGas. Therefore we should not treat gas limits as a fixed value of 21k, and should continue to use the same approach as before. More info on current Arbitrum gas behavior:
- https://developer.offchainlabs.com/arbos/gas
- https://developer.offchainlabs.com/arbos/l1-pricing
- https://medium.com/offchainlabs/understanding-arbitrum-2-dimensional-fees-fd1d582596c9

fix: arbitrum eth withdrawals now work (reverts a3e9648)

---

umbra-js/src/classes/Umbra.ts

Facilitates https://github.com/ScopeLift/umbra-protocol/pull/406, since the import from the contracts-core directory was causing some issues and the `Umbra.json` file wasn't published as part of the build
cc @wildmolasses @jferas @apbendi

chore: remove ABI import from contracts-core directory

---

frontend/src/components/BaseSelect.vue
frontend/src/pages/AccountSend.vue

Closes #294 
Style loosely mirrors what Uniswap does to show balances

feat: show token balances on send page dropdown

---

frontend/src/utils/address.ts
frontend/tsconfig.json

- Make isAddress more async, and handle errors in isAddress
Closes #373

Make isAddress more async

---

contracts-core/package.json
frontend/package.json
umbra-js/package.json
umbra-js/src/classes/StealthKeyRegistry.ts
umbra-js/src/classes/Umbra.ts
umbra-js/test/KeyPair.test.ts
umbra-js/test/StealthKeyRegistry.test.ts
umbra-js/test/Umbra.test.ts
umbra-js/test/utils.test.ts
yarn.lock

Enables support for ENS names with emojis, ref https://github.com/ethers-io/ethers.js/issues/2376

chore: bump ethers.js version

---

contracts-periphery/test/UniswapWithdrawHook.fork.1.t.sol

- Updates forge-std lib
- Moves `expectCall` out of helper function and loop
- Changes `bound` param for `sponsorFee` to have 0 as min instead of 1

Fix CI with contract tests `expectCall` update

---

frontend/package.json
frontend/src/pages/AccountSend.vue
frontend/src/shims-vue.d.ts
frontend/src/utils/validation.ts
frontend/test/validation.test.ts
yarn.lock

- Check if the ENS name contains a confusable character and raise a warning if there is and there are no errors.
Closes #154

Warn if confusable characters are used in ENS name

---

frontend/src/store/wallet.ts

- Removed `iconUrls` from `eip3085Chain`. There are a number of open issues related to this on Metamask's [repo](https://github.com/search?q=repo%3AMetaMask%2Fmetamask-extension+addEthereumChain&type=issues&p=1)
- Removed `address` and `logoURI` from `nativeCurrency` to be EIP3085 compatible.
- Spread `blockExplorerUrls` and `rpcUrls` from proxy arrays to actually arrays before calling `wallet_addEthereumChain`
Now users will be prompted to add the new network to their wallet when they select it from the network dropdown menu.

Add new network to wallet fix Closes #537

---

frontend/src/components/AccountReceiveTable.vue

- Sort order does not become confused when the unsorted state is removed
Closes #540

Remove unsorted state

---

frontend/src/components/AccountReceiveTable.vue

- Fix copy behavior on the receive table
Closes #501

Add provider so copy works again

---

frontend/src/pages/AccountSend.vue

- There is a gap, but there shouldn't be overlapping messages.
[Screencast from 2023-06-22 13-01-51.webm](https://github.com/ScopeLift/umbra-protocol/assets/12705146/64506a78-3981-4cdc-b5d3-fa30250fc65d)
Closes #525

Fix overlapping messages

---

frontend/src/components/AccountReceiveTable.vue

- Sort amount by real value
Closes #550

Sort amount correctly

---

frontend/src/components/AccountSentTable.vue
frontend/src/i18n/locales/en-US.json
frontend/src/i18n/locales/zh-CN.json
frontend/src/pages/AccountSent.vue
frontend/src/utils/account-send.ts
frontend/test/account-send.test.ts

- Add a button to clear send history
Closes #471

Add clear history button

---

frontend/src/pages/AccountReceive.vue
umbra-js/src/classes/Umbra.ts
umbra-js/src/utils/constants.ts
umbra-js/src/utils/utils.ts

One of the improvements listed in https://github.com/ScopeLift/umbra-protocol/issues/266

Scan from user registered block

---

frontend/package.json
frontend/src/pages/AccountSend.vue
frontend/src/utils/validation.ts
frontend/test/validation.test.ts
yarn.lock

- Use ens normalize to detect confusable, illegal characters and illegal mixtures of unicode characters. This should conform better with ENS compared to `unicode-confusables`.
Closes #552

Use ens normalize instead of confusable

---

umbra-js/src/classes/Umbra.ts
umbra-js/src/utils/utils.ts

Fix for receive page scanning on Gnosis Chain, which currently throws `Internal JSON-RPC error`
Regression: 
Filtering announcements no longer returns an empty array when the startBlock is `undefined` instead it reverts back to `chainConfig` default `startblock`. Will create an issue to handle this elsewhere using `isAccountSetup` from `walletStore`. See https://github.com/ScopeLift/umbra-protocol/issues/569

Fix Gnosis scanning error -- Block range too wide

---

umbra-js/src/classes/Umbra.ts

Fixes [CI failures](https://github.com/ScopeLift/umbra-protocol/actions/runs/5556669269/jobs/10149474025?pr=558) in #573 #558 
**Issue**: Because `typeof window` is undefined during the test, the `try` `catch` block of code is skipped, resulting in an empty `userAnnouncements` array being returned. Therefore, all tests involving the `Umbra.scan` function was failing the CI.
**Solution**: If conditions for the `try` `catch` block aren't met, yield announcements from logs:
```
397    yield await this.fetchAllAnnouncementFromLogs(startBlock, endBlock);
```
Because `fetchAllAnnouncements` is now a AsyncGenerator function that `yields` announcements as they are fetched, also update the previous call to `fetchAllAnnouncementFromLogs` to
```
394    yield await …
```

Fix #558 CI

---

frontend/src/components/AccountReceiveTable.vue

Without a working mainnet RPC url `lookupOrReturnAddresses` was throwing an error causing the table to be stuck at a loading state with spinning icons. This PR adds a `try-catch` block to handle the error.

Use try catch block for address lookups Closes #582

---

umbra-js/src/utils/utils.ts

Add timeout to `stealthKeyLogs` query from registry

---

frontend/package.json
frontend/src/store/wallet.ts
yarn.lock

- Remove ledger module and dependencies

Remove ledger module

---

frontend/src/css/app.sass
frontend/src/pages/AccountSend.vue

Check recipient addresses for ENS confusables in batch send

---

frontend/src/components/AccountReceiveTable.vue
frontend/src/store/wallet.ts
frontend/src/utils/utils.ts

Resolves #367 
Made inability to connect to Umbra API a softer error so native tokens can be transferred

Better frontend handling when API is down

---

frontend/src/pages/AccountSend.vue

Resolves #646 
Remove offending Recipient ID string from error message for more consistent layout.
Because the existing ENS lookup error message contains the variable length Recipient ID, when it is long is can cause the error message to sometime pop down over either the confusables warning message or the next batch send label. The variable length of the error string popped down by the base-input component makes layout calculations problematic.
Made the change to substitute a fixed length error message here in the frontend rather than in UmbraJS to ensure users of UmbraJS aren't affected by any messaging changes the thrown error. 
Dependance on a specific string from UmbraJS is somewhat brittle, if there's a better way to accomplish, please mention in review.

Remove potential ENS lookup error message overlap on batch sends.

---

frontend/src/components/AccountReceiveTable.vue
frontend/src/components/models.ts
frontend/src/store/settings.ts
frontend/src/utils/umbra-api.ts

Resolves #309 
Added most recently obtained version of Umbra relayer/API to local storage..
At startup, on creation of Umbra relayer/API.. and on every interaction between the front-end and the API.. the API version is returned in the API's response to the front-end, and the version and local storage are used in the following way:
1. Attempt to read the most recently saved API version from local storage.
2. If the version does not exist in local storage, save the most recently received version from the API to local storage.
3. If the version does exist in local storage, compare it to the version received from the API.. if the major/minor numbers differ, the following actions are taken:
a. The saved API version in local storage is cleared.
b. The user is alerted.
c. The user is forced to …

Detect Umbra relayer/API version change and force reload

---

umbra-js/src/utils/utils.ts

updates the error verbiage when no stealth key changed event data is returned from the subgraph to "Address has not registered stealth keys..." since they probably (near certainly) didn't register yet (hence no events).
originally it would show an error message that potentially wasn't as clear.

fix: show addr not registered error when no event data from subgraph
